[build]
  base = "website"
  command = "npm run build"
  publish = "dist"
[[redirects]]
  from = "https://littlegeniuss.netlify.app/*"
  to = "https://littlegeniusisland.ca/:splat"
  status = 301
  force = true